### PR TITLE
Add secret mounts support to init-container

### PR DESCRIPTION
**Pull request by prajjwaldimri**
Midgard's migrations import and use midgard's internal services, which in turn require access to credentials that are saved in a secret file named midgard-files. init-container would also require access to this file.

### CODE REVIEW

**Comment by prajjwaldimri** [comment]
Tested by deploying a new app in arg-685 cluster.

**Comment by suryaoruganti** [comment]
is the feature adding same secret mounts but on init-containers?

**Comment by prajjwaldimri** [comment]
Yes. We require it for the migrator.

**Review by PrashantRaj18198 — APPROVED** [review]
lgtm ☘️

**Comment by suryaoruganti** [comment]
please add these to stateful, job, and cronjob apps as well. Keeping it consistent for ease of maintenance.

**Comment by suryaoruganti** [comment]
lgtm after adding

**Pull request merged**
