### PR TITLE
removes art-$appName-secret from templates

### PR DESCRIPTION
**Pull request by prajjwaldimri**

### CODE REVIEW

**Comment by suryaoruganti** [comment]
is this change backward compatible? previously deployed apps should not break.

**Comment by suryaoruganti** [comment]
are `envFrom` fields in art.yaml appended or replaced by midgard?

**Comment by prajjwaldimri** [comment]
envFrom fields are appended similarly to secretMounts

**Comment by prajjwaldimri** [comment]
It becomes backwards compatible after the migration gets run on the DB and the code gets updated. (If only chart change is pushed, it is not backwards compatible with the current code) Should we upgrade the minor version for this?

**Comment by suryaoruganti** [comment]
let's chat - I want to bring some hygiene to this repo

**Comment by prajjwaldimri** [comment]
@suryaoruganti Changed base to v0.6.0. Please re-review

**Comment by suryaoruganti** [comment]
lgtm

**Comment by prajjwaldimri** [comment]
@suryaoruganti This should be merged before backend changes go through, as we have given charts a version bump.

**Pull request merged**
